### ISSUE TITLE
Create documentation

### ISSUE THREAD

**Issue by jensschuppe** [systopia/be.aivl.i3val#11]
Best to be done in MKDocs format for publishing on https://docs.civicrm.org

**Comment by bjendres** [comment]
Done, thanks @jensschuppe . I changed a few minor things, but overall great docs!

**Comment by jensschuppe** [comment]
Thanks, I filed a [merge request](https://lab.civicrm.org/documentation/docs-books/merge_requests/13) in the docs-books repository for the docs to appear on https://docs.civicrm.org.
