### ISSUE TITLE
change activity for SEPA does not update BIC

### ISSUE THREAD

**Issue by jojowork** [systopia/be.aivl.i3val#30]
the transmitted value is different from the current value
but still it is not adopted to the value that should be applied
and as a result it is also not applied
are there any conditions I do not know of, or is this a bug?

![i3val-bug](https://user-images.githubusercontent.com/40828981/91280224-c3830900-e786-11ea-869a-45660e70b583.png)

**Comment by bjendres** [comment]
This seems to only happen when the "Little BIC Extension" is not installed. In this case, the IBAN/BIC service is still called, but returns no BIC. That's fine, but the evaluation then simply clears the field.

**Comment by jojowork** [comment]
Feedback from our client: The solution is working. Can you add it to the next release?

**Comment by bjendres** [comment]
It's been tagged with ``0.5-alpha10`` and will later be released with ``0.5``
